CREATE TYPE account_type AS ENUM ('COMPANY', 'EMPLOYEE');

CREATE TABLE IF NOT EXISTS account (
  id       SERIAL          PRIMARY KEY,
  type     account_type    NOT NULL DEFAULT 'EMPLOYEE',
  balance  NUMERIC(15,2)   NOT NULL DEFAULT 0.00,
  bank_id  INTEGER         NOT NULL
    REFERENCES bank(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bank (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    swift_code VARCHAR(20) UNIQUE NOT NULL
);
